# HyprEmoji Configuration

# Keybind to open hypremoji
bind = SUPER, period, exec, hypremoji  # Open Emoji Picker 🔍💪

# Window rules for HyprEmoji
windowrule = float true, match:title ^(HyprEmoji)$ 

